import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { createClient } from '@supabase/supabase-js'
import {
  createDonImageFingerprint,
  encodeDonImageFingerprint,
  isPlausibleDonImage,
} from '../lib/donImageFingerprint'

type DonCatalogRow = {
  variant_id: string
  r2_image_url: string | null
  source_image_url: string | null
}

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY
if (!supabaseUrl || !serviceRoleKey) throw new Error('Credenziali Supabase mancanti.')

const supabase = createClient(supabaseUrl, serviceRoleKey, {
  auth: { persistSession: false, autoRefreshToken: false },
})

const mapLimit = async <T, R>(items: T[], limit: number, task: (item: T) => Promise<R>) => {
  const output = new Array<R>(items.length)
  let cursor = 0
  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (cursor < items.length) {
      const index = cursor++
      output[index] = await task(items[index])
    }
  })
  await Promise.all(workers)
  return output
}

const main = async () => {
  const { data, error } = await supabase
    .from('card_catalog')
    .select('variant_id,r2_image_url,source_image_url')
    .or('card_type.eq.DON!!,rarity.eq.DON!!')
    .order('variant_id')
  if (error) throw error

  const rows = (data || []) as DonCatalogRow[]
  const signatures = await mapLimit(rows, 8, async row => {
    const imageUrls = [...new Set([row.r2_image_url, row.source_image_url].filter(Boolean))] as string[]
    for (const imageUrl of imageUrls) {
      try {
        const response = await fetch(imageUrl, { signal: AbortSignal.timeout(10_000) })
        if (!response.ok) continue
        const image = Buffer.from(await response.arrayBuffer())
        if (!(await isPlausibleDonImage(image))) continue
        const fingerprint = await createDonImageFingerprint(image)
        return [row.variant_id.toUpperCase(), encodeDonImageFingerprint(fingerprint)] as const
      } catch {
        // Try the next catalog image source.
      }
    }
    return null
  })

  const entries = signatures.filter((entry): entry is readonly [string, string] => Boolean(entry))
  const output = [
    '// Generated by scripts/generate-don-image-signatures.ts.',
    '// Regenerate after importing new DON images into card_catalog/R2.',
    `export const DON_IMAGE_SIGNATURES: Readonly<Record<string, string>> = ${JSON.stringify(Object.fromEntries(entries), null, 2)}`,
    '',
  ].join('\n')

  const outputPath = resolve('lib/donImageSignatures.generated.ts')
  await writeFile(outputPath, output, 'utf8')
  const indexedIds = new Set(entries.map(([variantId]) => variantId))
  console.log(JSON.stringify({
    catalogDon: rows.length,
    generated: entries.length,
    skipped: rows.filter(row => !indexedIds.has(row.variant_id.toUpperCase())).map(row => row.variant_id),
    outputPath,
  }))
}

main().catch(error => {
  console.error(error)
  process.exitCode = 1
})
